            // CHAPTER 21
// Q1
// var userinput=prompt()
// var userinput= userinput.toLowerCase

// Q2
// var userinput=prompt()
// var userinput= userinput.toLowerCase;
// var alphabet= "X"

// Q3
// var userinput=prompt()
// var userinput= userinput.toUpperCase;
// var alphabet= "Y"

// Q7
// var userinput=prompt("where do you live?")
// var firstChar=userinput.slice(0,1).toUpperCase;
// var remainChar=userinput.slice(1).toLowerCase;
// var combineInput=firstChar+remainChar;
// var cityArr=["karachi","multan","islamabad","peshawar"]
// for (var i=0;1<cityArr.length; i++){
//     if(combineInput === cityArr[i]){
//      console.log("match")
//     }
// }

           // CHAPTER 22-25
// Q10
// var aplha= "a,b,c,d"
// console.log(2)

// Q9
// var arr=["123","abc","bcd"]
// if(arr==="abc"){
    // console.log("abc")
// }

// Q16
// var str="1"
// var newStr="one"
// console.log(newStr.replace(str))

// Q13
// Cha=["horse","cheetah","lion","monkey"]
// var animalsName=Cha
// console.log(animalsName)

// Q17
var alph= "a,b,c"
var y=("a,j,z")
console.log(y.replace(alpha))


